a = input("Digite algo:")
print(f"O tipo primitivo desse valor é,{type(a)}")
print(f"É só um número? {a.isnumeric()}")
print(f"É alfabético? {a.isalpha()}")
print(f"É alfanumérico? {a.isalnum()}")
print(f"Só tem espaços? {a.isspace()}")
print(f"Só está em maiúsculas? {a.isupper()}")
print(f"Só está em minúsculas? {a.islower()}")
print(f"Está capitalizado? {a.istitle()}")
